name: Test package

on:
  push
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies and run tests
        run: uv run pytest --cov=src --cov-report=json

      - name: Get coverage percentage
        run: |
         export TOTAL=$(uv run python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
         echo "coverage=$TOTAL" >> $GITHUB_ENV
         
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a72d32f9e10c404f7738822dac068274
          filename: covbadge.json
          label: Test coverage
          message: ${{ env.coverage }}
          valColorRange: ${{ env.coverage }}
          maxColorRange: 100
          minColorRange: 0
